apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gobidder-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_API
          value: "http://auth-service:8081"
        - name: PAYMENT_API
          value: "http://payment-service:8082"
        - name: AUCTION_API
          value: "http://auction-service:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000
  type: NodePort
