services:
  auth-service:
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
  payment-service:
    build:
      context: ./services/PaymentService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network
  reverse-proxy:
    build:
      context: ./services/ReverseProxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 80:8080
    volumes:
      - ./services/ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
