services:
  auth-service:
    build:
      context: ./services
      dockerfile: AuthService/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
  auction-service:
    build:
      context: ./services
      dockerfile: AuctionService/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
  payment-service:
    build:
      context: ./services
      dockerfile: PaymentService/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network
  reverse-proxy:
    build:
      context: ./services/ReverseProxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - microservices-network
    depends_on:
      - reverse-proxy
      - auth-service

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
