services:
  auth_service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
  reverse_proxy:
    build:
      context: ./ReverseProxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 80:8080
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
