services:
  auth-service:
    build:
      context: ./services
      dockerfile: AuthService/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network

  auction-service:
    build:
      context: ./services
      dockerfile: AuctionService/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
  payment-service:
    build:
      context: ./services
      dockerfile: PaymentService/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network
      
  reverse-proxy:
    build:
      context: ./services/ReverseProxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - microservices-network
    depends_on:
      - reverse-proxy
      - auth-service

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - microservices-network

  kafka:
    build:
      context: ./services/Kafka
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - microservices-network
    depends_on:
      - zookeeper

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
  kafka-data:
  zookeeper-data: