services:
  auth1:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
