services:
  auth_service:
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - auth-data:/app/data
    networks:
      - microservices-network
    depends_on:
      - kafka

  reverse_proxy:
    build:
      context: ./services/ReverseProxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 80:8080
    volumes:
      - ./services/ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - microservices-network

  kafka:
    build:
      context: ./services/Kafka
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - microservices-network
    depends_on:
      - zookeeper

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
  kafka-data:
  zookeeper-data: